
- name: Start client BeeGFS instance
  hosts: client
  become: true
  become_user: root
  tasks:
    - name: start mgmtd
      ansible.builtin.systemd_service:
        name: beegfs-mgmtd
        state: started
        enabled: true
    - name: start medadata
      ansible.builtin.systemd_service:
        name: beegfs-meta
        state: started
        enabled: true


- name: Start all BeeGFS instances
  hosts: coursemachines
  become: true
  become_user: root
  tasks:
    - name: start storage
      ansible.builtin.systemd_service:
        name: beegfs-storage
        state: started
        enabled: true
    - name: start helperd
      ansible.builtin.systemd_service:
        name: beegfs-helperd
        state: started
        enabled: true
    - name: start client
      ansible.builtin.systemd_service:
        name: beegfs-client
        state: started
        enabled: true
