version: '3'
services:
  prefect:
    container_name: prefect
    image: prefecthq/prefect:2.14-python3.8-conda
    command: ["prefect", "server", "start"]
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:postgres@postgres/prefect
      EXTRA_PIP_PACKAGES: asyncpg psycopg2-binary
      PREFECT_API_URL: "http://127.0.0.1:4200/api"

    depends_on:
      - postgres
   
  postgres:
    container_name: postgres
    image: davidfrisch/postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    # volumes:
    #   - /data/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    restart: always
