version: "3.9"
services:

  ### Prefect postgres
  postgres:
    image: davidfrisch/postgres
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
    
  
