version: "3.8"
services:

  nginx:
    image: nginx:stable-alpine-slim
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - prefect

  ### Prefect postgres
  postgres:
    image: 10.0.8.191:5000/postgres
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data


  prefect:
    image: david/prefect:latest
    container_name: prefect
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    entrypoint: ['prefect', 'server', 'start', '--host', '0.0.0.0']
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/prefect
    deploy:
      placement:
        constraints:
          - node.role == manager
    expose:
      - 4200
    ports:
      - "4200:4200"
    volumes:
      - ./pipeline:/pipeline
      - ./data:/data

  agent:
    image: david/prefect:latest
    container_name: agent
    environment:
      - PREFECT_API_URL=http://ec2-35-178-107-122.eu-west-2.compute.amazonaws.com/api
    entrypoint: ['python3', '/app/pipeline/pipeline.py']



volumes:
  db: