
  - name: Update packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: NFS tools
    ansible.builtin.dnf:
      name: "nfs-utils"
      state: latest

  - name: Create the NFS share
    ansible.builtin.file:
      path: /mnt/data/shared
      state: directory
      group: ec2-user
      owner: ec2-user

  - name: Delete the existing line in /etc/exports
    ansible.builtin.lineinfile:
      path: /etc/exports
      state: absent
      regexp: "^/mnt/data/shared.*$"

  - name: Write in /etc/exports
    ansible.builtin.lineinfile:
      path: /etc/exports
      line: "/mnt/data/shared {{ item }}(rw,sync,no_root_squash)"
    with_items: "{{ groups['coursemachines'] }}"

  - name: Export the NFS share
    ansible.builtin.shell: exportfs -a

  - name: Enable the NFS server
    ansible.builtin.systemd:
      name: nfs-server
      enabled: yes
      state: started

  - name: NFS mountpoint
    ansible.builtin.file:
      path: /mnt/data/shared
      state: directory
      group: ec2-user
      owner: ec2-user

  - name: NFS fstab
    ansible.posix.mount:
      boot: true
      state: mounted
      fstype: nfs
      src: "{{ groups['client'][0] }}:/mnt/data/shared"
      path: /mnt/data/shared
      opts: defaults,_netdev
    