
- name: install git
  package:
    name: git
    state: present

- name: clone git repo
  shell:  |
    cd {{ base_repo_dir }} && \
    git clone https://{{ git_token }}@github.com/davidfrisch/cw_data_eng_2
