
- name: install git
  package:
    name: git
    state: present

- name: clone git repo
  shell:  |
    cd {{ base_repo_dir }} && \
    git clone https://{{ git_token }}@github.com/davidfrisch/cw_data_eng_2

- name: create environment
  shell: |
    cd {{ repo_dir }} && \
    python3 -m venv venv && \
    source venv/bin/activate 

- name: Change ownership of repo
  become: true
  file:
    path: "{{ repo_dir }}"
    owner: ec2-user
    group: ec2-user
    recurse: yes