---

- name: Change owner of repo dir
  file:
    path: "{{ repo_dir }}"
    owner: ec2-user
    group: ec2-user
    state: directory
    recurse: yes

- name: Update git repo
  shell:  |
    cd {{ repo_dir }} && \
    git pull https://{{ git_token }}@github.com/davidfrisch/cw_data_eng_2

- name: Run node_setup_script.sh with arguments
  command: " {{ repo_dir }}/scripts/node_setup_script.sh \
        -h {{ groups['client'][0] }} \
        -t {{ hf_token }} \
        -db audio_results \
        -du {{ pg_user }} \
        -dp {{ pg_password }} "
        
