global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.


scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100', '10.0.3.237:9100','10.0.10.132:9100','10.0.4.223:9100','ip-10-0-11-166:9100']


  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080','10.0.3.237:8080','10.0.10.132:8080','10.0.4.223:8080','ip-10-0-11-166:8080']