# - name: BeegGFS Common Configuration
#   hosts: coursemachines
#   become: true
#   become_user: root
#   tasks:

- name: Delete old beegfs-storage.conf
  ansible.builtin.file:
    path: /etc/beegfs/beegfs-storage.conf
    state: absent

- name: copy clean beegfs-storage in vm
  ansible.builtin.copy:
    src: beegfs-storage.conf
    dest: /etc/beegfs/beegfs-storage.conf
    owner: root
    group: root
    mode: 644

- name: stop storage
  ansible.builtin.systemd_service:
    name: beegfs-storage
    state: stopped
    enabled: true

- name: Clear old targets
  ansible.builtin.file:
    path: /mnt/data/beegfs_data/target
    state: absent

- name: Create target location
  ansible.builtin.file:
    path: /mnt/data/beegfs_data/target
    state: directory
- name: Configure client
  ansible.builtin.command:
    cmd: /opt/beegfs/sbin/beegfs-setup-storage -p /mnt/data/beegfs_data/target -m ip-10-0-7-16
- name: Auth file
  ansible.builtin.copy:
    src: connauthfile
    dest: /etc/beegfs/connauthfile
    owner: root
    group: root
    mode: 400
- name: fix storage conf
  ansible.builtin.replace:
    path: /etc/beegfs/beegfs-storage.conf
    regexp: 'connAuthFile                 ='
    replace: 'connAuthFile=/etc/beegfs/connauthfile'
- name: start storage
  ansible.builtin.systemd_service:
    name: beegfs-storage
    state: started
    enabled: true

