---

- name: Change owner of repo dir
  file:
    path: "{{ repo_dir }}"
    owner: ec2-user
    group: ec2-user
    state: directory
    recurse: yes

# TODO: Put it back when the script is ready
# - name: Update git repo
#   shell:  |
#     cd {{ repo_dir }} && \
#     git pull https://{{ git_token }}@github.com/davidfrisch/cw_data_eng_2


- name: Install nslookup with yum
  yum:
    name: bind-utils
    state: present

# TODO: Put it back when the script is ready
# - name: Update env vars 
#   shell: |
#     cd {{ repo_dir }} && ./scripts/setup_local_env.sh --hostname {{ groups['client'][0] }} --db-user {{ database_user }} --db-pass {{ database_pass }} 

# TODO Put it back when requirements.txt is ready
# - name: install requirements
#   shell: |
#     cd {{ repo_dir }} && \
#     source venv/bin/activate && \
#     pip install pip --upgrade && \
#     cd {{ repo_dir }} && \
#     TMPDIR=/mnt/data pip install . --no-cache --cache-dir=/mnt/data/pip_cache --no-cache