- name: Setup playbook
  hosts: client, clusters
  become: true

  tasks:
    - include_vars: vars.yml
    - include_vars: custom_vars.yml

    - name: Include common role
      import_role:
        name: common

    - name: Include NFS role
      import_role:
        name: nfs

    - name: Change owner of repo_dir to ec2-user
      ansible.builtin.file:
        path: "{{ repo_dir }}"
        owner: ec2-user
        group: ec2-user
        recurse: yes

