- name: Setup playbook
  hosts: coursemachines
  become: true

  tasks:
    - include_vars: vars.yml
    - include_vars: custom_vars.yml

    - name: Include common role
      import_role:
        name: common

    - name: Include beegfs role
      import_role:
        name: install_beegfs

