name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Hostname of the server'
        required: true
    

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run the setup script
        run: |
          ./scripts/node_setup_script.sh \
              -h ${{ github.event.inputs.host }} \
              -t ${{ secrets.HF_TOKEN }} \
              -dh postgres \
              -db audio_results \
              -du ${{ secrets.PG_USER }} \
              -dp ${{ secrets.PG_PASSWORD }} 

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker compose
        run: |
          docker-compose build
          docker-compose push
        